### ISSUE TITLE
Improve `ingress`

### ISSUE THREAD

**Issue by mathieu-benoit** [Humanitec-DemoOrg/traderx-demo#3]
Instead of having a dedicated `ingress` workload, let's remove it and use native ingress controller instead.

**Comment by cloudikeme** [comment]
> Instead of having a dedicated `ingress` workload, let's remove it and use native ingress controller instead.

Hey Mathieu, 
So i'm guessing that would be the NGINX Ingress Controller or which?

**Comment by mathieu-benoit** [comment]
Hi @cloudikeme, so the idea is to leverage how the `dns` and `route` resources work with `score-compose` and `score-k8s`.

The idea is that `ingress` Workload should be deleted and replaced by adding this `resources` part in each Workload (Score file) that needs to be exposed by the DNS:
```
...
resources:
  dns:
    type: dns
    id: dns
  route:
    type: route
    params:
      host: ${resources.dns.host}
      path: /FIXME
      port: 8080
```

You can check [what's defined in this file](https://github.com/Humanitec-DemoOrg/traderx-demo/blob/main/apps/ingress/nginx.traderx.conf.template) to back port them with the snippet above in the respective Score files.

`id: dns` will allow to have all the 

That could be a good exercise for you to try more Score ;) Feel free to open a PR where we could iterate on this.

This can be tested with `score-compose`, no need of `score-k8s`. Once validated and working successfully with `score-compose`, it will seamlessly work with `score-k8s`, and this no matter if it's an Ingress controller or Gateway API :) We'll see about this later.
